name: Build

on: 
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_REGION: ${{ secrets.S3_REGION }}
          S3_REGION_ENDPOINT: ${{ secrets.S3_REGION_ENDPOINT }}
        run: |
          bash build.sh
      - name: Run docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: docker-compose up -d
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: "30s"
      - name: Test the IPFS API server
        run: docker run --network host appropriate/curl -s --retry 10 --retry-connrefused -X POST http://127.0.0.1:5001/api/v0/version
      - name: Collect docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
        with:
          dest: "./logs"
      - name: Tar logs
        if: failure()
        run: tar cvzf ./logs.tgz ./logs
      - name: Upload logs to GitHub
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: logs.tgz
          path: ./logs.tgz